apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: application-sample
    appstudio.openshift.io/component: node-express-hello-uetw
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: node-express-hello-uetw
  namespace: default
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_burrsutter_node-express-hello
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/burrsutter/node-express-hello
