apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-express-hello-uetw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-express-hello-uetw
    app.kubernetes.io/part-of: application-sample
  name: node-express-hello-uetw
  namespace: default
spec:
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: node-express-hello-uetw
    weight: 100
status: {}
